name: Deploy Portfolio to AWS Amplify

on:
  push:
    branches:
<<<<<<< HEAD
      - development  # Change this if you use a different branch for deployment
=======
      - main  # Change this if you use a different branch for deployment
>>>>>>> d6af183c959bf4d92016e4097efc02f80ba80c23

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    

    - name: Trigger AWS Amplify Deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'  # Update with your AWS region
        AMPLIFY_APP_ID: 'd147cvyfumg9ll'  # Replace with your actual Amplify App ID
        BRANCH: 'main'  # Update this if you deploy from a different branch
      run: |
<<<<<<< HEAD
        aws amplify start-job --app-id $AMPLIFY_APP_ID --branch-name $BRANCH --job-type RELEASE
=======
        aws amplify start-job --app-id $AMPLIFY_APP_ID --branch-name $BRANCH --job-type RELEASE
>>>>>>> d6af183c959bf4d92016e4097efc02f80ba80c23
