name: Deploy Portfolio to AWS Amplify

on:
  push:
    branches:
      - main  # Change this if you use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Trigger AWS Amplify Deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'  # Update with your AWS region
        AMPLIFY_APP_ID: 'd3kdcn9gi1j9y2'  # Replace with your actual Amplify App ID
        BRANCH: 'main'  # Update this if you deploy from a different branch
      run: |
        aws amplify start-job --app-id $AMPLIFY_APP_ID --branch-name $BRANCH --job-type RELEASE
